# Generated by Django 5.0.3 on 2024-05-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepie',
            old_name='recepie_description',
            new_name='text',
        ),
    ]
