# Generated by Django 5.0.6 on 2024-05-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegs', '0003_rename_recepie_receipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='recepie_name',
            new_name='receipe_name',
        ),
    ]
